spring:
  application:
    name: rjsoft-jycj-admin-main
  #thymelea模板配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/

  devtools:
      restart:
        enabled: true

server:
  port: 8088

#eureka common
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://192.168.111.118:1111/eureka/

#端点 默认值为health,info
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info

#ribbon:
#  OkToRetryOnAllOperations: false


